// Redux actions
export const LOAD_ALL_AUTHORS = 'LOAD_ALL_AUTHORS';

export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const LOAD_ALL_COURSES = 'LOAD_ALL_COURSES';

export const ERROR_FETCHING_DATA = 'ERROR_FETCHING_DATA';
export const CLEAR_ERROR = 'CLEAR_ERROR';

// Redux saga actions
export const AUTHORS_FETCH_REQUESTED = 'AUTHORS_FETCH_REQUESTED';

export const COURSES_FETCH_REQUESTED = 'COURSES_FETCH_REQUESTED';
export const COURSE_ADD_REQUESTED = 'COURSE_ADD_REQUESTED';
export const COURSE_DELETE_REQUESTED = 'COURSE_DELETE_REQUESTED';
export const COURSE_UPDATE_REQUESTED = 'COURSE_UPDATE_REQUESTED';
